version: "3"
services:
  selenium-chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - ./app:/app
    working_dir: /app
  app:
    image: node:latest
    tty: true
    volumes:
      - ./app:/app
      - ./node/scripts:/scripts
    depends_on:
      - selenium-chrome
    environment:
      - WORKDIR_DOCKER=/app
      - SCRIPTDIR_DOCKER=/scripts
    working_dir: /app
    command: /scripts/entrypoint.sh