version: "3"
services:
  selenium-chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - ./app:/app
    working_dir: /app
  app:
    build:
      context: ./
      dockerfile: dockerfile_python
    tty: true
    volumes:
      - ./app:/app
    depends_on:
      - selenium-chrome
    working_dir: /app